# Copyright 2023 The Google Research Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Utility library of instructions."""

import functools
import random
import re

import immutabledict
import nltk


def download_nltk_resources():
    """Download 'punkt' if not already installed"""
    try:
        nltk.data.find("tokenizers/punkt")
    except LookupError:
        nltk.download("punkt")


download_nltk_resources()

WORD_LIST_EN = [
    "western",
    "sentence",
    "signal",
    "dump",
    "spot",
    "opposite",
    "bottom",
    "potato",
    "administration",
    "working",
    "welcome",
    "morning",
    "good",
    "agency",
    "primary",
    "wish",
    "responsibility",
    "press",
    "problem",
    "president",
    "steal",
    "brush",
    "read",
    "type",
    "beat",
    "trainer",
    "growth",
    "lock",
    "bone",
    "case",
    "equal",
    "comfortable",
    "region",
    "replacement",
    "performance",
    "mate",
    "walk",
    "medicine",
    "film",
    "thing",
    "rock",
    "tap",
    "total",
    "competition",
    "ease",
    "south",
    "establishment",
    "gather",
    "parking",
    "world",
    "plenty",
    "breath",
    "claim",
    "alcohol",
    "trade",
    "dear",
    "highlight",
    "street",
    "matter",
    "decision",
    "mess",
    "agreement",
    "studio",
    "coach",
    "assist",
    "brain",
    "wing",
    "style",
    "private",
    "top",
    "brown",
    "leg",
    "buy",
    "procedure",
    "method",
    "speed",
    "high",
    "company",
    "valuable",
    "pie",
    "analyst",
    "session",
    "pattern",
    "district",
    "pleasure",
    "dinner",
    "swimming",
    "joke",
    "order",
    "plate",
    "department",
    "motor",
    "cell",
    "spend",
    "cabinet",
    "difference",
    "power",
    "examination",
    "engine",
    "horse",
    "dimension",
    "pay",
    "toe",
    "curve",
    "literature",
    "bother",
    "fire",
    "possibility",
    "debate",
    "activity",
    "passage",
    "hello",
    "cycle",
    "background",
    "quiet",
    "author",
    "effect",
    "actor",
    "page",
    "bicycle",
    "error",
    "throat",
    "attack",
    "character",
    "phone",
    "tea",
    "increase",
    "outcome",
    "file",
    "specific",
    "inspector",
    "internal",
    "potential",
    "staff",
    "building",
    "employer",
    "shoe",
    "hand",
    "direction",
    "garden",
    "purchase",
    "interview",
    "study",
    "recognition",
    "member",
    "spiritual",
    "oven",
    "sandwich",
    "weird",
    "passenger",
    "particular",
    "response",
    "reaction",
    "size",
    "variation",
    "a",
    "cancel",
    "candy",
    "exit",
    "guest",
    "condition",
    "fly",
    "price",
    "weakness",
    "convert",
    "hotel",
    "great",
    "mouth",
    "mind",
    "song",
    "sugar",
    "suspect",
    "telephone",
    "ear",
    "roof",
    "paint",
    "refrigerator",
    "organization",
    "jury",
    "reward",
    "engineering",
    "day",
    "possession",
    "crew",
    "bar",
    "road",
    "description",
    "celebration",
    "score",
    "mark",
    "letter",
    "shower",
    "suggestion",
    "sir",
    "luck",
    "national",
    "progress",
    "hall",
    "stroke",
    "theory",
    "offer",
    "story",
    "tax",
    "definition",
    "history",
    "ride",
    "medium",
    "opening",
    "glass",
    "elevator",
    "stomach",
    "question",
    "ability",
    "leading",
    "village",
    "computer",
    "city",
    "grand",
    "confidence",
    "candle",
    "priest",
    "recommendation",
    "point",
    "necessary",
    "body",
    "desk",
    "secret",
    "horror",
    "noise",
    "culture",
    "warning",
    "water",
    "round",
    "diet",
    "flower",
    "bus",
    "tough",
    "permission",
    "week",
    "prompt",
    "connection",
    "abuse",
    "height",
    "save",
    "corner",
    "border",
    "stress",
    "drive",
    "stop",
    "rip",
    "meal",
    "listen",
    "confusion",
    "girlfriend",
    "living",
    "relation",
    "significance",
    "plan",
    "creative",
    "atmosphere",
    "blame",
    "invite",
    "housing",
    "paper",
    "drink",
    "roll",
    "silver",
    "drunk",
    "age",
    "damage",
    "smoke",
    "environment",
    "pack",
    "savings",
    "influence",
    "tourist",

    "rain",
    "post",
    "sign",
    "grandmother",
    "run",
    "profit",
    "push",
    "clerk",
    "final",
    "wine",
    "swim",
    "pause",
    "stuff",
    "singer",
    "funeral",
    "average",
    "source",
    "scene",
    "tradition",
    "personal",
    "snow",
    "nobody",
    "distance",
    "sort",
    "sensitive",
    "animal",
    "major",
    "negotiation",
    "click",
    "mood",
    "period",
    "arrival",
    "expression",
    "holiday",
    "repeat",
    "dust",
    "closet",
    "gold",
    "bad",
    "sail",
    "combination",
    "clothes",
    "emphasis",
    "duty",
    "black",
    "step",
    "school",
    "jump",
    "document",
    "professional",
    "lip",
    "chemical",
    "front",
    "wake",
    "while",
    "inside",
    "watch",
    "row",
    "subject",
    "penalty",
    "balance",
    "possible",
    "adult",
    "aside",
    "sample",
    "appeal",
    "wedding",
    "depth",
    "king",
    "award",
    "wife",
    "blow",
    "site",
    "camp",
    "music",
    "safe",
    "gift",
    "fault",
    "guess",
    "act",
    "shame",
    "drama",
    "capital",
    "exam",
    "stupid",
    "record",
    "sound",
    "swing",
    "novel",
    "minimum",
    "ratio",
    "machine",
    "shape",
    "lead",
    "operation",
    "salary",
    "cloud",
    "affair",
    "hit",
    "chapter",
    "stage",
    "quantity",
    "access",
    "army",
    "chain",
    "traffic",
    "kick",
    "analysis",
    "airport",
    "time",
    "vacation",
    "philosophy",
    "ball",
    "chest",
    "thanks",
    "place",
    "mountain",
    "advertising",
    "red",
    "past",
    "rent",
    "return",
    "tour",
    "house",
    "construction",
    "net",
    "native",
    "war",
    "figure",
    "fee",
    "spray",
    "user",
    "dirt",
    "shot",
    "task",
    "stick",
    "friend",
    "software",
    "promotion",
    "interaction",
    "surround",
    "block",
    "purpose",
    "practice",
    "conflict",
    "routine",
    "requirement",
    "bonus",
    "hole",
    "state",
    "junior",
    "sweet",
    "catch",
    "tear",
    "fold",
    "wall",
    "editor",
    "life",
    "position",
    "pound",
    "respect",
    "bathroom",
    "coat",
    "script",
    "job",
    "teach",
    "birth",
    "view",
    "resolve",
    "theme",
    "employee",
    "doubt",
    "market",
    "education",
    "serve",
    "recover",
    "tone",
    "harm",
    "miss",
    "union",
    "understanding",
    "cow",
    "river",
    "association",
    "concept",
    "training",
    "recipe",
    "relationship",
    "reserve",
    "depression",
    "proof",
    "hair",
    "revenue",
    "independent",
    "lift",
    "assignment",
    "temporary",
    "amount",
    "loss",
    "edge",
    "track",
    "check",
    "rope",
    "estimate",
    "pollution",
    "stable",
    "message",
    "delivery",
    "perspective",
    "mirror",
    "assistant",
    "representative",
    "witness",
    "nature",
    "judge",
    "fruit",
    "tip",
    "devil",
    "town",
    "emergency",
    "upper",
    "drop",
    "stay",
    "human",
    "neck",
    "speaker",
    "network",
    "sing",
    "resist",
    "league",
    "trip",
    "signature",
    "lawyer",
    "importance",
    "gas",
    "choice",
    "engineer",
    "success",
    "part",
    "external",
    "worker",
    "simple",
    "quarter",
    "student",
    "heart",
    "pass",
    "spite",
    "shift",
    "rough",
    "lady",
    "grass",
    "community",
    "garage",
    "youth",
    "standard",
    "skirt",
    "promise",
    "blind",
    "television",
    "disease",
    "commission",
    "positive",
    "energy",
    "calm",
    "presence",
    "tune",
    "basis",
    "preference",
    "head",
    "common",
    "cut",
    "somewhere",
    "presentation",
    "current",
    "thought",
    "revolution",
    "effort",
    "master",
    "implement",
    "republic",
    "floor",
    "principle",
    "stranger",
    "shoulder",
    "grade",
    "button",
    "tennis",
    "police",
    "collection",
    "account",
    "register",
    "glove",
    "divide",
    "professor",
    "chair",
    "priority",
    "combine",
    "peace",
    "extension",
    "maybe",

    "evening",
    "frame",
    "sister",
    "wave",
    "code",
    "application",
    "mouse",
    "match",
    "counter",
    "bottle",
    "half",
    "cheek",
    "resolution",
    "back",
    "knowledge",
    "make",
    "discussion",
    "screw",
    "length",
    "accident",
    "battle",
    "dress",
    "knee",
    "log",
    "package",
    "it",
    "turn",
    "hearing",
    "newspaper",
    "layer",
    "wealth",
    "profile",
    "imagination",
    "answer",
    "weekend",
    "teacher",
    "appearance",
    "meet",
    "bike",
    "rise",
    "belt",
    "crash",
    "bowl",
    "equivalent",
    "support",
    "image",
    "poem",
    "risk",
    "excitement",
    "remote",
    "secretary",
    "public",
    "produce",
    "plane",
    "display",
    "money",
    "sand",
    "situation",
    "punch",
    "customer",
    "title",
    "shake",
    "mortgage",
    "option",
    "number",
    "pop",
    "window",
    "extent",
    "nothing",
    "experience",
    "opinion",
    "departure",
    "dance",
    "indication",
    "boy",
    "material",
    "band",
    "leader",
    "sun",
    "beautiful",
    "muscle",
    "farmer",
    "variety",
    "fat",
    "handle",
    "director",
    "opportunity",
    "calendar",
    "outside",
    "pace",
    "bath",
    "fish",
    "consequence",
    "put",
    "owner",
    "go",
    "doctor",
    "information",
    "share",
    "hurt",
    "protection",
    "career",
    "finance",
    "force",
    "golf",
    "garbage",
    "aspect",
    "kid",
    "food",
    "boot",
    "milk",
    "respond",
    "objective",
    "reality",
    "raw",
    "ring",
    "mall",
    "one",
    "impact",
    "area",
    "news",
    "international",
    "series",
    "impress",
    "mother",
    "shelter",
    "strike",
    "loan",
    "month",
    "seat",
    "anything",
    "entertainment",
    "familiar",
    "clue",
    "year",
    "glad",
    "supermarket",
    "natural",
    "god",
    "cost",
    "conversation",
    "tie",
    "ruin",
    "comfort",
    "earth",
    "storm",
    "percentage",
    "assistance",
    "budget",
    "strength",
    "beginning",
    "sleep",
    "other",
    "young",
    "unit",
    "fill",
    "store",
    "desire",
    "hide",
    "value",
    "cup",
    "maintenance",
    "nurse",
    "function",
    "tower",
    "role",
    "class",
    "camera",
    "database",
    "panic",
    "nation",
    "basket",
    "ice",
    "art",
    "spirit",
    "chart",
    "exchange",
    "feedback",
    "statement",
    "reputation",
    "search",
    "hunt",
    "exercise",
    "nasty",
    "notice",
    "male",
    "yard",
    "annual",
    "collar",
    "date",
    "platform",
    "plant",
    "fortune",
    "passion",
    "friendship",
    "spread",
    "cancer",
    "ticket",
    "attitude",
    "island",
    "active",
    "object",
    "service",
    "buyer",
    "bite",
    "card",
    "face",
    "steak",
    "proposal",
    "patient",
    "heat",
    "rule",
    "resident",
    "broad",
    "politics",
    "west",
    "knife",
    "expert",
    "girl",
    "design",
    "salt",
    "baseball",
    "grab",
    "inspection",
    "cousin",
    "couple",
    "magazine",
    "cook",
    "dependent",
    "security",
    "chicken",
    "version",
    "currency",
    "ladder",
    "scheme",
    "kitchen",
    "employment",
    "local",
    "attention",
    "manager",
    "fact",
    "cover",
    "sad",
    "guard",
    "relative",
    "county",
    "rate",
    "lunch",
    "program",
    "initiative",
    "gear",
    "bridge",
    "breast",
    "talk",
    "dish",
    "guarantee",
    "beer",
    "vehicle",
    "reception",
    "woman",
    "substance",
    "copy",
    "lecture",
    "advantage",
    "park",
    "cold",
    "death",
    "mix",
    "hold",
    "scale",
    "tomorrow",
    "blood",
    "request",
    "green",
    "cookie",
    "church",
    "strip",
    "forever",
    "beyond",
    "debt",
    "tackle",
    "wash",
    "following",
    "feel",
    "maximum",
    "sector",
    "sea",
    "property",
    "economics",
    "menu",
    "bench",
    "try",
    "language",
    "start",
    "call",
    "solid",
    "address",
    "income",
    "foot",
    "senior",
    "honey",
    "few",
    "mixture",
    "cash",
    "grocery",
    "link",
    "map",
    "form",
    "factor",
    "pot",
    "model",
    "writer",
    "farm",
    "winter",
    "skill",
    "anywhere",
    "birthday",
    "policy",
    "release",
    "husband",
    "lab",
    "hurry",
    "mail",
    "equipment",
    "sink",
    "pair",
    "driver",
    "consideration",
    "leather",
    "skin",
    "blue",
    "boat",
    "sale",
    "brick",
    "two",
    "feed",
    "square",
    "dot",
    "rush",
    "dream",
    "location",
    "afternoon",
    "manufacturer",
    "control",
    "occasion",
    "trouble",
    "introduction",
    "advice",
    "bet",
    "eat",
    "kill",
    "category",
    "manner",
    "office",
    "estate",
    "pride",
    "awareness",
    "slip",
    "crack",
    "client",
    "nail",
    "shoot",
    "membership",
    "soft",
    "anybody",
    "web",
    "official",
    "individual",
    "pizza",
    "interest",
    "bag",
    "spell",
    "profession",
    "queen",
    "deal",
    "resource",
    "ship",
    "guy",
    "chocolate",
    "joint",
    "formal",
    "upstairs",
    "car",
    "resort",
    "abroad",
    "dealer",
    "associate",
    "finger",
    "surgery",
    "comment",
    "team",
    "detail",
    "crazy",
    "path",
    "tale",
    "initial",
    "arm",
    "radio",
    "demand",
    "single",

    "draw",
    "yellow",
    "contest",
    "piece",
    "quote",
    "pull",
    "commercial",
    "shirt",
    "contribution",
    "cream",
    "channel",
    "suit",
    "discipline",
    "instruction",
    "concert",
    "speech",
    "low",
    "effective",
    "hang",
    "scratch",
    "industry",
    "breakfast",
    "lay",
    "join",
    "metal",
    "bedroom",
    "minute",
    "product",
    "rest",
    "temperature",
    "many",
    "give",
    "argument",
    "print",
    "purple",
    "laugh",
    "health",
    "credit",
    "investment",
    "sell",
    "setting",
    "lesson",
    "egg",
    "middle",
    "marriage",
    "level",
    "evidence",
    "phrase",
    "love",
    "self",
    "benefit",
    "guidance",
    "affect",
    "you",
    "dad",
    "anxiety",
    "special",
    "boyfriend",
    "test",
    "blank",
    "payment",
    "soup",
    "obligation",
    "reply",
    "smile",
    "deep",
    "complaint",
    "addition",
    "review",
    "box",
    "towel",
    "minor",
    "fun",
    "soil",
    "issue",
    "cigarette",
    "internet",
    "gain",
    "tell",
    "entry",
    "spare",
    "incident",
    "family",
    "refuse",
    "branch",
    "can",
    "pen",
    "grandfather",
    "constant",
    "tank",
    "uncle",
    "climate",
    "ground",
    "volume",
    "communication",
    "kind",
    "poet",
    "child",
    "screen",
    "mine",
    "quit",
    "gene",
    "lack",
    "charity",
    "memory",
    "tooth",
    "fear",
    "mention",
    "marketing",
    "reveal",
    "reason",
    "court",
    "season",
    "freedom",
    "land",
    "sport",
    "audience",
    "classroom",
    "law",
    "hook",
    "win",
    "carry",
    "eye",
    "smell",
    "distribution",
    "research",
    "country",
    "dare",
    "hope",
    "whereas",
    "stretch",
    "library",
    "if",
    "delay",
    "college",
    "plastic",
    "book",
    "present",
    "use",
    "worry",
    "champion",
    "goal",
    "economy",
    "march",
    "election",
    "reflection",
    "midnight",
    "slide",
    "inflation",
    "action",
    "challenge",
    "guitar",
    "coast",
    "apple",
    "campaign",
    "field",
    "jacket",
    "sense",
    "way",
    "visual",
    "remove",
    "weather",
    "trash",
    "cable",
    "regret",
    "buddy",
    "beach",
    "historian",
    "courage",
    "sympathy",
    "truck",
    "tension",
    "permit",
    "nose",
    "bed",
    "son",
    "person",
    "base",
    "meat",
    "usual",
    "air",
    "meeting",
    "worth",
    "game",
    "independence",
    "physical",
    "brief",
    "play",
    "raise",
    "board",
    "she",
    "key",
    "writing",
    "pick",
    "command",
    "party",
    "yesterday",
    "spring",
    "candidate",
    "physics",
    "university",
    "concern",
    "development",
    "change",
    "string",
    "target",
    "instance",
    "room",
    "bitter",
    "bird",
    "football",
    "normal",
    "split",
    "impression",
    "wood",
    "long",
    "meaning",
    "stock",
    "cap",
    "leadership",
    "media",
    "ambition",
    "fishing",
    "essay",
    "salad",
    "repair",
    "today",
    "designer",
    "night",
    "bank",
    "drawing",
    "inevitable",
    "phase",
    "vast",
    "chip",
    "anger",
    "switch",
    "cry",
    "twist",
    "personality",
    "attempt",
    "storage",
    "being",
    "preparation",
    "bat",
    "selection",
    "white",
    "technology",
    "contract",
    "side",
    "section",
    "station",
    "till",
    "structure",
    "tongue",
    "taste",
    "truth",
    "difficulty",
    "group",
    "limit",
    "main",
    "move",
    "feeling",
    "light",
    "example",
    "mission",
    "might",
    "wait",
    "wheel",
    "shop",
    "host",
    "classic",
    "alternative",
    "cause",
    "agent",
    "consist",
    "table",
    "airline",
    "text",
    "pool",
    "craft",
    "range",
    "fuel",
    "tool",
    "partner",
    "load",
    "entrance",
    "deposit",
    "hate",
    "article",
    "video",
    "summer",
    "feature",
    "extreme",
    "mobile",
    "hospital",
    "flight",
    "fall",
    "pension",
    "piano",
    "fail",
    "result",
    "rub",
    "gap",
    "system",
    "report",
    "suck",
    "ordinary",
    "wind",
    "nerve",
    "ask",
    "shine",
    "note",
    "line",
    "mom",
    "perception",
    "brother",
    "reference",
    "bend",
    "charge",
    "treat",
    "trick",
    "term",
    "homework",
    "bake",
    "bid",
    "status",
    "project",
    "strategy",
    "orange",
    "let",
    "enthusiasm",
    "parent",
    "concentrate",
    "device",
    "travel",
    "poetry",
    "business",
    "society",
    "kiss",
    "end",
    "vegetable",
    "employ",
    "schedule",
    "hour",
    "brave",
    "focus",
    "process",
    "movie",
    "illegal",
    "general",
    "coffee",
    "ad",
    "highway",
    "chemistry",
    "psychology",
    "hire",
    "bell",
    "conference",
    "relief",
    "show",
    "neat",
    "funny",
    "weight",
    "quality",
    "club",
    "daughter",
    "zone",
    "touch",
    "tonight",
    "shock",
    "burn",
    "excuse",
    "name",
    "survey",
    "landscape",
    "advance",
    "satisfaction",
    "bread",
    "disaster",
    "item",
    "hat",
    "prior",
    "shopping",
    "visit",
    "east",
    "photo",
    "home",
    "idea",
    "father",
    "comparison",
    "cat",
    "pipe",
    "winner",
    "count",
    "lake",
    "fight",
    "prize",
    "foundation",
    "dog",
    "keep",
    "ideal",
    "fan",
    "struggle",
    "peak",
    "safety",
    "solution",
    "hell",
    "conclusion",
    "population",
    "strain",
    "alarm",
    "measurement",
    "second",
    "train",
    "race",
    "due",
    "insurance",
    "boss",
    "tree",
    "monitor",
    "sick",
    "course",
    "drag",
    "appointment",
    "slice",
    "still",
    "care",
    "patience",
    "rich",
    "escape",
    "emotion",
    "royal",
    "female",
    "childhood",
    "government",
    "picture",
    "will",
    "sock",
    "big",
    "gate",
    "oil",
    "cross",
    "pin",
    "improvement",
    "championship",
    "silly",
    "help",
    "sky",
    "pitch",
    "man",
    "diamond",
    "most",
    "transition",
    "work",
    "science",
    "committee",
    "moment",
    "fix",
    "teaching",
    "dig",
    "specialist",
    "complex",
    "guide",
    "people",
    "dead",
    "voice",
    "original",
    "break",
    "topic",
    "data",
    "degree",
    "reading",
    "recording",
    "bunch",
    "reach",
    "judgment",
    "lie",
    "regular",
    "set",
    "painting",
    "mode",
    "list",
    "player",
    "bear",
    "north",
    "wonder",
    "carpet",
    "heavy",
    "officer",
    "negative",
    "clock",
    "unique",
    "baby",
    "pain",
    "assumption",
    "disk",
    "iron",
    "bill",
    "drawer",

    "look",
    "double",
    "mistake",
    "finish",
    "future",
    "brilliant",
    "contact",
    "math",
    "rice",
    "leave",
    "restaurant",
    "discount",
    "sex",
    "virus",
    "bit",
    "trust",
    "event",
    "wear",
    "juice",
    "failure",
    "bug",
    "context",
    "mud",
    "whole",
    "wrap",
    "intention",
    "draft",
    "pressure",
    "cake",
    "dark",
    "explanation",
    "space",
    "angle",
    "word",
    "efficiency",
    "management",
    "habit",
    "star",
    "chance",
    "finding",
    "transportation",
    "stand",
    "criticism",
    "flow",
    "door",
    "injury",
    "insect",
    "surprise",
    "apartment",
]  # pylint: disable=line-too-long

WORD_LIST_IT = [
    "occidentale",
    "frase", "sentenza",
    "segnale",
    "discarica", "scaricare",
    "posto", "macchia", "punto",
    "opposto", "di fronte",
    "fondo", "parte inferiore",
    "patata",
    "amministrazione", "governo", "gestione",
    "lavoro", "funzionante",
    "benvenuto",
    "mattina",
    "buono", "bene",
    "agenzia", "ente",
    "primario", "principale",
    "desiderio", "augurio",
    "responsabilità", "compito",
    "stampa", "premere",
    "problema",
    "presidente",
    "rubare",
    "spazzola", "spazzolare",
    "leggere",
    "tipo", "digitare",
    "battere", "sconfiggere",
    "allenatore", "istruttore",
    "crescita", "sviluppo",
    "lucchetto", "chiudere a chiave",
    "osso",
    "caso", "scatola",
    "uguale", "pari",
    "comodo", "confortevole",
    "regione", "zona",
    "sostituzione", "rimpiazzo",
    "prestazione", "esecuzione",
    "compagno", "partner",
    "camminare", "passeggiata",
    "medicina", "farmaco",
    "film", "pellicola",
    "cosa", "oggetto",
    "roccia", "sasso", "rock",
    "toccare", "rubinetto",
    "totale", "complessivo",
    "competizione", "gara",
    "facilità", "agio",
    "sud",
    "fondazione", "stabilimento", "locale",
    "raccogliere", "radunare",
    "parcheggio",
    "mondo",
    "abbondanza", "molto",
    "respiro",
    "rivendicare", "affermazione",
    "alcol",
    "commercio", "scambio",
    "caro", "gentile",
    "evidenziare", "punto saliente",
    "strada", "via",
    "questione", "materia", "sostanza",
    "decisione",
    "disordine", "casino",
    "accordo", "patto", "contratto",
    "studio", "atelier", "sala di registrazione",
    "allenatore", "coach",
    "assistere", "aiutare",
    "cervello",
    "ala",
    "stile",
    "privato",
    "cima", "superiore",
    "marrone",
    "gamba", "zampa",
    "comprare", "acquistare",
    "procedura",
    "metodo",
    "velocità",

    "alto", "sballo",
    "azienda", "compagnia", "società",
    "prezioso", "di valore",
    "torta", "crostata",
    "analista",
    "sessione", "seduta",
    "schema", "modello", "motivo",
    "distretto", "quartiere",
    "piacere", "godimento",
    "cena",
    "nuoto",
    "scherzo", "barzelletta",
    "ordine", "ordinare",
    "piatto", "lastra",
    "dipartimento", "reparto",
    "motore",
    "cella", "cellulare",
    "spendere", "trascorrere",
    "armadio", "gabinetto",
    "differenza",
    "potere", "energia", "forza",
    "esame", "esaminazione",
    "motore",
    "cavallo",
    "dimensione", "misura",
    "pagare", "paga",
    "dito del piede", "alluce",
    "curva",
    "letteratura",
    "disturbare", "seccare",
    "fuoco", "incendio", "sparare",
    "possibilità",
    "dibattito", "discussione",
    "attività",
    "passaggio", "corridoio", "brano",
    "ciao", "salve",
    "ciclo", "giro",
    "sfondo", "retroscena",
    "silenzioso", "tranquillo",
    "autore", "scrittore",
    "effetto",
    "attore",
    "pagina",
    "bicicletta",
    "errore",
    "gola",
    "attacco", "aggredire",
    "personaggio", "carattere",
    "telefono",
    "tè",
    "aumento", "crescita",
    "risultato", "esito",
    "file", "schedario", "fascicolo",
    "specifico", "particolare",
    "ispettore",
    "interno",
    "potenziale",
    "personale", "staff",
    "edificio", "costruzione",
    "datore di lavoro",
    "scarpa",
    "mano",
    "direzione", "orientamento",
    "giardino",
    "acquisto", "comprare",
    "colloquio", "intervista",
    "studio", "ricerca",
    "riconoscimento",
    "membro", "iscritto",
    "spirituale",
    "forno",
    "panino", "sandwich",
    "strano", "bizzarro",
    "passeggero",
    "particolare", "specifico",
    "risposta",
    "reazione",
    "dimensione", "taglia",
    "variazione",
    "un", "una",
    "annullare", "cancellare",
    "caramella",
    "uscita",
    "ospite",
    "condizione", "stato",
    "volare", "mosca",
    "prezzo",
    "debolezza",
    "convertire", "trasformare",
    "hotel", "albergo",
    "grande", "ottimo",
    "bocca",
    "mente",
    "canzone", "brano",
    "zucchero",
    "sospettare", "sospetto",
    "telefono", "apparecchio telefonico",
    "orecchio",
    "tetto",
    "vernice", "dipingere",
    "frigorifero",
    "organizzazione", "ente",
    "giuria",
    "ricompensa", "premio",
    "ingegneria",
    "giorno",
    "possesso", "bene",
    "equipaggio",
    "bar", "locale",
    "strada",
    "descrizione",
    "celebrazione", "festeggiamento",
    "punteggio", "partitura",
    "segno", "voto", "marchio",
    "lettera",
    "doccia",
    "suggerimento", "proposta",
    "signore", "sir",
    "fortuna",
    "nazionale",
    "progresso", "avanzamento",
    "sala", "atrio",
    "colpo", "ictus",
    "teoria",
    "offerta", "proposta",
    "storia", "racconto",
    "tassa",
    "definizione",
    "storia", "storia passata",
    "cavalcare", "corsa", "giro",
    "mezzo", "medio",
    "apertura", "inizio",
    "vetro", "bicchiere",
    "ascensore",
    "stomaco", "pancia",
    "domanda", "quesito",
    "abilità", "capacità",
    "leader", "principale",
    "villaggio", "paese",
    "computer",
    "città",
    "grande", "maestoso",
    "fiducia", "sicurezza di sé",
    "candela",
    "prete", "sacerdote",
    "raccomandazione", "consiglio",
    "punto", "segnalare",
    "necessario", "indispensabile",
    "corpo",
    "scrivania", "banco",
    "segreto",
    "orrore", "paura",
    "rumore",
    "cultura",
    "avvertimento", "avviso",
    "acqua",
    "rotondo", "giro",
    "dieta",
    "fiore",
    "autobus", "bus",
    "duro", "tosto", "difficile",
    "permesso", "autorizzazione",
    "settimana",
    "pronto", "sollecito",
    "connessione", "collegamento",
    "abuso", "maltrattamento",
    "altezza",
    "salvare", "risparmiare",
    "angolo", "spigolo",
    "confine", "frontiera",
    "stress", "tensione",
    "guidare", "corsa",
    "fermarsi", "stop",
    "strappare", "lacerare",
    "pasto",
    "ascoltare",
    "confusione",
    "fidanzata",
    "vivere", "abitazione",
    "relazione", "parentela",
    "importanza", "significato",
    "piano", "programma",
    "creativo",
    "atmosfera", "ambiente",
    "colpa",
    "invitare", "invito",
    "alloggio", "abitazione",
    "carta", "giornale",
    "bevanda", "bere",
    "rotolo", "rotolare",
    "argento",
    "ubriaco",
    "età",
    "danno",
    "fumo", "fumare",
    "ambiente",
    "pacchetto", "confezione",
    "risparmi",
    "influenza", "influsso",
    "turista",

    "pioggia",
    "posta", "palo", "inviare",
    "segno", "cartello", "firmare",
    "nonna",
    "correre", "gestire",
    "profitto", "guadagno",
    "spingere", "pressione",
    "impiegato", "commesso",
    "finale", "definitivo",
    "vino",
    "nuotare",
    "pausa", "interruzione",
    "roba", "materiale",
    "cantante",
    "funerale",
    "media", "medio",
    "fonte", "origine",
    "scena", "scenario",
    "tradizione",
    "personale", "privato",
    "neve",
    "nessuno",
    "distanza",
    "tipo", "ordinare",
    "sensibile", "delicato",
    "animale",
    "maggiore", "importante",
    "negoziazione", "trattativa",
    "clic", "scatto",
    "umore",
    "periodo", "epoca",
    "arrivo",
    "espressione",
    "vacanza", "festività",
    "ripetere",
    "polvere",
    "armadio", "ripostiglio",
    "oro",
    "cattivo",
    "vela", "navigare",
    "combinazione", "unione",
    "vestiti", "abiti",
    "enfasi", "accento",
    "dovere", "obbligo",
    "nero",
    "passo", "scalino",
    "scuola",
    "saltare",
    "documento",
    "professionale",
    "labbro",
    "chimico",
    "fronte", "davanti",
    "sveglia", "svegliarsi",
    "mentre",
    "dentro",
    "orologio", "guardare",
    "fila", "riga", "remare",
    "soggetto", "materia",
    "penalità", "sanzione",
    "equilibrio", "bilancia",
    "possibile",
    "adulto",
    "da parte", "a lato",
    "campione", "esempio",
    "appello", "ricorso",
    "matrimonio", "nozze",
    "profondità",
    "re",
    "premio", "riconoscimento",
    "moglie",
    "soffiare", "colpo",
    "sito", "luogo",
    "campo", "accampamento",
    "musica",
    "sicuro", "cassaforte",
    "regalo", "dono",
    "colpa", "guasto",
    "indovinare", "supporre",
    "atto", "agire",
    "vergogna",
    "dramma",
    "capitale",
    "esame", "prova",
    "stupido",
    "record", "registrazione", "primato",
    "suono",
    "altalena", "oscillare",
    "romanzo",
    "minimo",
    "rapporto", "proporzione",
    "macchina",
    "forma", "sagoma",
    "piombo", "guidare", "condurre",
    "operazione", "intervento",
    "stipendio", "salario",
    "nuvola",
    "affare", "relazione",
    "colpire", "successo",
    "capitolo",
    "palcoscenico", "fase",
    "quantità",
    "accesso",
    "esercito",
    "catena",
    "traffico",
    "calcio", "colpo",
    "analisi",
    "aeroporto",
    "tempo", "ora",
    "vacanza",
    "filosofia",
    "palla", "ballo",
    "petto", "cassa",
    "grazie",
    "posto", "luogo",
    "montagna",
    "pubblicità",
    "rosso",
    "passato",
    "affitto", "noleggio",
    "ritorno", "rendere",
    "tour", "giro",
    "casa",
    "costruzione", "cantiere",
    "rete", "netto",
    "nativo", "indigeno",
    "guerra",
    "figura", "numero",
    "tassa", "compenso",
    "spruzzare", "spruzzo",
    "utente",
    "sporcizia", "terra",
    "colpo", "sparare",
    "compito",
    "bastone", "attaccare",
    "amico",
    "software",
    "promozione", "avanzamento",
    "interazione",
    "circondare",
    "blocco", "isolato",
    "scopo", "finalità",
    "pratica", "allenamento",
    "conflitto",
    "routine", "abitudine",
    "requisito",
    "bonus", "premio",
    "buco",
    "stato", "condizione",
    "junior", "giovane",
    "dolce", "caramella",
    "afferrare", "catturare",
    "lacrima", "strappare",
    "piegare", "piega",
    "muro", "parete",
    "redattore", "editor",
    "vita",
    "posizione", "carica",
    "libbra", "martellare",
    "rispetto",
    "bagno",
    "cappotto", "mantello",
    "copione", "script",
    "lavoro", "impiego",
    "insegnare",
    "nascita",
    "vista", "opinione",
    "risolvere",
    "tema", "argomento",
    "dipendente",
    "dubbio",
    "mercato",
    "istruzione", "educazione",
    "servire",
    "recuperare",
    "tono",
    "danno", "male",
    "perdere", "sentire la mancanza",
    "unione", "sindacato",
    "comprensione", "intesa",
    "mucca",
    "fiume",
    "associazione",
    "concetto",
    "formazione", "addestramento",
    "ricetta",
    "relazione",
    "riserva", "prenotare",
    "depressione", "avvallamento",
    "prova", "dimostrazione",
    "capelli", "pelo",
    "entrate", "ricavi",
    "indipendente",
    "sollevare", "ascensore",
    "compito", "assegnazione",
    "temporaneo", "provvisorio",
    "ammontare", "quantità",
    "perdita",
    "bordo", "orlo",
    "traccia", "pista",
    "controllare", "assegno",
    "corda", "fune",
    "stima", "preventivo",
    "inquinamento",
    "stabile", "scuderia",
    "messaggio",
    "consegna", "spedizione",
    "prospettiva", "punto di vista",
    "specchio",
    "assistente",
    "rappresentante",
    "testimone",
    "natura",
    "giudice",
    "frutto",
    "punta", "mancia", "consiglio",
    "diavolo",
    "cittadina", "paese",
    "emergenza",
    "superiore", "alto",
    "goccia", "lasciare",
    "soggiorno", "restare",
    "umano",
    "collo",
    "altoparlante", "oratore",
    "rete",
    "cantare",
    "resistere",
    "lega", "campionato",
    "viaggio", "gita",
    "firma",
    "avvocato",
    "importanza",
    "gas",
    "scelta",
    "ingegnere",
    "successo",
    "parte",
    "esterno",
    "lavoratore",
    "semplice",
    "quarto", "trimestre",
    "studente",
    "cuore",
    "passare", "biglietto d’ingresso",
    "dispetto",
    "turno", "spostamento",
    "ruvido", "difficile",
    "signora", "dama",
    "erba", "prato",
    "comunità",
    "garage",
    "gioventù", "giovane età",
    "standard",
    "gonna",
    "promessa",
    "cieco",
    "televisione",
    "malattia",
    "commissione", "incarico",
    "positivo",
    "energia",
    "calmo", "tranquillo",
    "presenza",
    "melodia", "accordare",
    "base", "fondamento",
    "preferenza",
    "testa", "capo",
    "comune", "ordinario",
    "tagliare", "ferita",
    "da qualche parte",
    "presentazione", "relazione",
    "corrente", "attuale",
    "pensiero",
    "rivoluzione",
    "sforzo",
    "maestro", "padrone",
    "attuare", "strumento",
    "repubblica",
    "pavimento", "piano",
    "principio",
    "sconosciuto", "estraneo",
    "spalla",
    "voto", "grado",
    "bottone",
    "tennis",
    "polizia",
    "collezione", "raccolta",
    "conto", "account",
    "registro", "registrare",
    "guanto",
    "dividere",
    "professore",
    "sedia", "poltrona",
    "priorità",
    "combinare", "unire",
    "pace",
    "estensione", "prolungamento",
    "forse",

    "sera",
    "cornice", "struttura", "fotogramma",
    "sorella",
    "onda", "salutare",
    "codice",
    "applicazione", "domanda",
    "topo", "mouse",
    "partita", "incontro", "fiammifero", "abbinare",
    "bancone", "contatore",
    "bottiglia",
    "metà",
    "guancia",
    "risoluzione", "determinazione",
    "schiena", "indietro", "retro",
    "conoscenza", "sapere",
    "fare",
    "discussione",
    "vite", "avvitare",
    "lunghezza",
    "incidente",
    "battaglia",
    "vestito", "abito",
    "ginocchio",
    "registro", "tronco",
    "pacchetto", "confezione",
    "esso", "ciò",
    "girare", "svolta",
    "udienza", "udito",
    "giornale",
    "strato",
    "ricchezza",
    "profilo",
    "immaginazione",
    "risposta",
    "fine settimana", "weekend",
    "insegnante", "maestro",
    "aspetto", "apparizione",
    "incontrare",
    "bicicletta", "moto",
    "alzarsi", "sorgere",
    "cintura",
    "incidente", "schianto",
    "ciotola",
    "equivalente",
    "supporto", "sostegno",
    "immagine",
    "poesia",
    "rischio",
    "eccitazione", "entusiasmo",
    "remoto", "telecomando",
    "segretaria", "segretario",
    "pubblico",
    "produrre", "prodotti",
    "aereo", "piano",
    "schermo", "mostrare",
    "denaro", "soldi",
    "sabbia",
    "situazione",
    "pugno", "pugnalata",
    "cliente",
    "titolo",
    "scuotere", "stretta di mano",
    "mutuo", "ipoteca",
    "opzione",
    "numero",
    "scoppio", "pop",
    "finestra",
    "estensione", "portata",
    "niente",
    "esperienza",
    "opinione",
    "partenza",
    "danza", "ballo",
    "indicazione", "segno",
    "ragazzo",
    "materiale",
    "banda", "fascia", "gruppo musicale",
    "leader", "capo",
    "sole",
    "bello", "bella",
    "muscolo",
    "contadino", "agricoltore",
    "varietà",
    "grasso",
    "manico", "gestire",
    "direttore", "regista",
    "opportunità",
    "calendario",
    "fuori", "esterno",
    "andatura", "ritmo",
    "bagno",
    "pesce", "pescare",
    "conseguenza",
    "mettere",
    "proprietario",
    "andare",
    "medico", "dottore",
    "informazioni",
    "condividere", "quota",
    "ferire", "male",
    "protezione",
    "carriera",
    "finanza",
    "forza",
    "golf",
    "spazzatura", "immondizia",
    "aspetto", "punto di vista",
    "bambino", "ragazzino",
    "cibo",
    "stivale",
    "latte",
    "rispondere",
    "obiettivo", "scopo",
    "realtà",
    "crudo", "grezzo",
    "anello", "squillo",
    "centro commerciale",
    "uno",
    "impatto", "influenza",
    "area", "zona",
    "notizie", "news",
    "internazionale",
    "serie",
    "impressionare",
    "madre",
    "rifugio", "shelter",
    "sciopero", "colpire",
    "prestito",
    "mese",
    "sedile", "posto",
    "qualsiasi cosa",
    "intrattenimento",
    "familiare", "conosciuto",
    "indizio",
    "anno",
    "contento", "lieto",
    "supermercato",
    "naturale",
    "dio",
    "costo",
    "conversazione",
    "cravatta", "legare",
    "rovina", "distruggere",
    "comodità", "conforto",
    "terra",
    "tempesta",
    "percentuale",
    "assistenza", "aiuto",
    "bilancio",
    "forza", "vigore",
    "inizio",
    "sonno", "dormire",
    "altro",
    "giovane",
    "unità",
    "riempire",
    "negozio", "conservare",
    "desiderio",
    "nascondere",
    "valore",
    "tazza", "coppa",
    "manutenzione",
    "infermiera",
    "funzione",
    "torre",
    "ruolo",
    "classe", "lezione",
    "fotocamera", "telecamera",
    "database",
    "panico",
    "nazione",
    "cesto", "canestro",
    "ghiaccio",
    "arte",
    "spirito", "anima",
    "grafico",
    "scambio",
    "feedback", "riscontro",
    "dichiarazione",
    "reputazione",
    "ricerca",
    "caccia",
    "esercizio",
    "cattivo", "sgradevole",
    "avviso", "notare",
    "maschio",
    "cortile", "giardino",
    "annuale",
    "collare", "colletto",
    "data", "appuntamento", "dattero",
    "piattaforma", "banchina",
    "pianta", "fabbrica",
    "fortuna", "ricchezza",
    "passione",
    "amicizia",
    "diffondere", "spalmare",
    "cancro",
    "biglietto", "ticket",
    "atteggiamento",
    "isola",
    "attivo",
    "oggetto", "opporre",
    "servizio",
    "acquirente", "compratore",
    "morso", "mordere",
    "carta", "tessera",
    "faccia", "viso",
    "bistecca",
    "proposta",
    "paziente", "malato",
    "calore", "riscaldare",
    "regola", "dominare",
    "residente", "abitante",
    "ampio", "largo",
    "politica",
    "ovest", "occidente",
    "coltello",
    "esperto",
    "ragazza",
    "disegno", "progettare",
    "sale",
    "baseball",
    "afferrare", "prendere",
    "ispezione",
    "cugino", "cugina",
    "coppia",
    "rivista",
    "cuoco", "cucinare",
    "dipendente",
    "sicurezza",
    "pollo",
    "versione",
    "valuta", "moneta",
    "scala a pioli",
    "schema", "piano",
    "cucina",
    "impiego", "occupazione",
    "locale",
    "attenzione",
    "manager", "responsabile",
    "fatto",
    "coprire", "copertina",
    "triste",
    "guardia", "sorvegliare",
    "parente", "relativo",
    "contea", "provincia",
    "tasso", "tariffa",
    "pranzo",
    "programma",
    "iniziativa",
    "ingranaggio", "attrezzatura",
    "ponte",
    "seno", "petto",
    "parlare", "discorso",
    "piatto vivanda",
    "garanzia",
    "birra",
    "veicolo",
    "ricevimento", "accoglienza",
    "donna",
    "sostanza", "materia",
    "copia", "copiare",
    "lezione", "conferenza",
    "vantaggio",
    "parco",
    "freddo",
    "morte",
    "mescolare",
    "tenere", "prendere",
    "scala", "bilancia",
    "domani",
    "sangue",
    "richiesta",
    "verde",
    "biscotto",
    "chiesa",
    "strisciare", "spogliarello",
    "per sempre",
    "oltre",
    "debito",
    "placcaggio", "affrontare",
    "lavare",
    "seguente",
    "sentire", "provare",
    "massimo",
    "settore",
    "mare",
    "proprietà",
    "economia",
    "menu",
    "panchina", "tribunale",
    "provare", "tentare",
    "lingua",
    "iniziare",
    "chiamata", "telefonare",
    "solido",
    "indirizzo",
    "reddito",
    "piede",
    "senior", "anziano",
    "miele",
    "pochi",
    "miscela",
    "contanti",
    "drogheria", "alimentari",
    "collegamento", "link",
    "mappa",
    "modulo", "forma",
    "fattore",
    "pentola",
    "modello",
    "scrittore", "autore",
    "fattoria",
    "inverno",
    "abilità",
    "ovunque",
    "compleanno",
    "politica",
    "rilascio", "pubblicare",
    "marito",
    "laboratorio",
    "fretta",
    "posta",
    "attrezzatura",
    "lavandino", "affondare",
    "paio", "coppia",
    "autista",
    "considerazione",
    "pelle", "cuoio",
    "pelle", "cute",
    "blu",
    "barca",
    "vendita",
    "mattone",
    "due",
    "nutrire", "alimentare",
    "quadrato", "piazza",
    "punto", "puntino",
    "corsa", "fretta",
    "sogno",
    "posizione", "luogo",
    "pomeriggio",
    "produttore",
    "controllo",
    "occasione",
    "problema", "guaio",
    "introduzione",
    "consiglio",
    "scommessa",
    "mangiare",
    "uccidere",
    "categoria",
    "modo", "maniera",
    "ufficio",
    "proprietà", "tenuta",
    "orgoglio",
    "consapevolezza",
    "scivolare", "slip",
    "crepa", "fessura",
    "cliente",
    "unghia", "chiodo",
    "sparare", "scattare",
    "iscrizione", "abbonamento",
    "morbido", "soffice",
    "chiunque",
    "rete", "web",
    "ufficiale",
    "individuo",
    "pizza",
    "interesse",
    "borsa", "sacca",
    "incantesimo", "scrivere",
    "professione",
    "regina",
    "accordo", "affare",
    "risorsa",
    "nave", "spedire",
    "tipo", "tizio",
    "cioccolato",
    "articolazione", "congiunto",
    "formale",
    "di sopra", "piano superiore",
    "auto", "macchina",
    "resort", "villaggio turistico",
    "all’estero",
    "rivenditore", "dealer",
    "associare", "collega",
    "dito",
    "chirurgia", "operazione",
    "commento",
    "squadra", "team",
    "dettaglio",
    "pazzo",
    "sentiero", "percorso",
    "racconto", "fiaba",
    "iniziale",
    "braccio",
    "radio",
    "domanda", "richiesta",
    "singolo", "celibe", "singola",

    "disegnare", "pareggio", "attrarre", "estrarre",
    "giallo",
    "gara", "concorso", "contestare",
    "pezzo", "brano",
    "citazione", "quotare", "preventivo",
    "tirare", "trazione",
    "commerciale", "spot pubblicitario",
    "camicia", "maglietta",
    "contributo", "apporto",
    "crema", "panna",
    "canale", "canalizzare",
    "abito", "completo", "causa legale", "stare bene a",
    "disciplina", "disciplinare",
    "istruzione", "direttiva",
    "concerto", "intesa",
    "discorso", "parola",
    "basso",
    "efficace", "in vigore",
    "appendere", "impiccare", "restare in linea",
    "graffiare", "graffio", "grattare",
    "industria", "settore",
    "colazione",
    "posare", "sdraiare", "deporre", "laico",
    "unirsi", "giuntura", "congiungere",
    "metallo", "metal",
    "camera da letto",
    "minuto", "minuzioso",
    "prodotto",
    "riposo", "resto", "riposare",
    "temperatura",
    "molti", "tanti",
    "dare", "regalare", "cedere",
    "argomentazione", "lite", "discussione",
    "stampare", "stampa", "impronta",
    "viola", "porpora",
    "ridere", "risata",
    "salute",
    "credito", "riconoscimento",
    "investimento",
    "vendere", "svendere",
    "ambientazione", "impostazione", "scenario", "contesto",
    "lezione", "insegnamento",
    "uovo",
    "medio", "mezzo", "centrale",
    "matrimonio", "nozze",
    "livello",
    "prova", "evidenza", "indizio",
    "frase", "locuzione", "espressione",
    "amore", "amare",
    "sé", "se stesso", "auto-",
    "beneficio", "vantaggio", "benefit",
    "guida", "orientamento",
    "influenzare", "colpire",
    "tu", "voi", "Lei",
    "papà", "babbo", "padre",
    "ansia", "agitazione",
    "speciale", "particolare",
    "fidanzato", "ragazzo",
    "test", "esame", "prova",
    "vuoto", "in bianco",
    "pagamento",
    "zuppa", "minestra", "brodo",
    "obbligo",
    "rispondere", "risposta",
    "sorriso", "sorridere",
    "profondo",
    "lamentela", "reclamo", "querela",
    "aggiunta", "addizione",
    "recensione", "revisione", "rivedere",
    "scatola", "riquadro", "ring",
    "asciugamano", "salvietta",
    "minore", "secondario", "minorenne",
    "divertimento", "divertente",
    "suolo", "terreno", "sporcare",
    "questione", "problema", "emissione", "pubblicare",
    "sigaretta",
    "internet", "rete",
    "guadagno", "ottenere", "aumentare",
    "dire", "raccontare",
    "ingresso", "voce", "iscrizione",
    "di scorta", "risparmiare",
    "incidente", "episodio",
    "famiglia",
    "rifiutare", "rifiuti",
    "filiale", "ramo", "branca",
    "lattina", "barattolo", "potere", "inscatolare",
    "penna", "recinto",
    "nonno",
    "costante",
    "serbatoio", "carro armato", "vasca",
    "zio",
    "clima",
    "terra", "suolo", "fondare",
    "volume",
    "comunicazione",
    "gentile", "tipo",
    "poeta", "poetessa",
    "bambino", "figlio",
    "schermo", "selezionare",
    "mio", "miniera", "mina",
    "smettere", "abbandonare", "licenziarsi",
    "gene",
    "mancanza", "scarsità", "mancare",
    "carità", "beneficenza", "ente benefico",
    "memoria", "ricordo",
    "dente",
    "paura", "temere",
    "menzionare", "menzione", "citare",
    "marketing",
    "rivelare", "svelare",
    "ragione", "motivo", "ragionare",
    "tribunale", "corte", "campo",
    "stagione", "condire",
    "libertà",
    "terra", "atterrare", "sbarcare", "terreno",
    "sport",
    "pubblico", "platea",
    "aula",
    "legge", "diritto",
    "gancio", "agganciare",
    "vincere", "vittoria",
    "portare", "trasportare",
    "occhio",
    "odore", "annusare", "puzzare",
    "distribuzione",
    "ricerca", "fare ricerca",
    "paese", "campagna",
    "osare", "ardire",
    "speranza", "sperare",
    "mentre", "considerato che",
    "allungare", "tratto",
    "biblioteca",
    "se",
    "ritardo", "ritardare",
    "università", "college",
    "plastica", "plastico",
    "libro", "prenotare",
    "presente", "regalo", "presentare",
    "uso", "usare", "utilizzo",
    "preoccuparsi", "preoccupazione",
    "campione", "sostenere",
    "obiettivo", "rete",
    "economia", "risparmio",
    "marzo", "marcia", "marciare",
    "elezione",
    "riflessione", "riflesso",
    "mezzanotte",
    "scivolare", "diapositiva", "scivolo",
    "inflazione", "gonfiaggio",
    "azione", "causa",
    "sfida", "contestare",
    "chitarra",
    "costa",
    "mela",
    "campagna",
    "campo", "settore",
    "giacca", "giubbotto",
    "senso", "percepire",
    "modo", "via", "strada", "maniera",
    "visivo", "visuale",
    "rimuovere", "togliere",
    "meteo", "tempo atmosferico",
    "spazzatura", "buttare",
    "cavo", "tv via cavo",
    "rimpianto", "pentirsi",
    "amico", "compare",
    "spiaggia",
    "storico", "storica",
    "coraggio",
    "simpatia", "compassione",
    "camion",
    "tensione",
    "permesso", "permettere",
    "naso",
    "letto", "aiuola",
    "figlio",
    "persona",
    "base", "basare",
    "carne",
    "solito", "abituale",
    "aria", "aspetto",
    "riunione", "incontro",
    "valore", "vale la pena",
    "gioco", "partita", "selvaggina",
    "indipendenza",
    "fisico", "visita medica",
    "breve", "memoria",
    "giocare", "recitare", "opera teatrale",
    "aumentare", "sollevare", "aumento",
    "tavola", "consiglio", "imbarcare",
    "lei",
    "chiave", "tasto", "fondamentale",
    "scrittura",
    "scegliere", "raccogliere", "piccone",
    "comando", "ordinare",
    "festa", "partito", "parte",
    "ieri",
    "primavera", "molla", "sorgente", "saltare",
    "candidato", "candidata",
    "fisica",
    "università",
    "preoccupazione", "interessare", "impresa",
    "sviluppo",
    "cambiamento", "cambiare", "spiccioli",
    "corda", "filo", "stringa",
    "bersaglio", "obiettivo", "prendere di mira",
    "istanza", "esempio",
    "stanza", "spazio",
    "amaro", "acre", "aspro",
    "uccello",
    "calcio", "football americano",
    "normale",
    "dividere", "spaccare", "divisione",
    "impressione", "impronta",
    "legno", "bosco",
    "lungo", "bramare",
    "significato", "senso",
    "scorta", "azione", "magazzino",
    "cappellino", "tappo", "tetto",
    "leadership", "dirigenza", "capacità di guida",
    "media", "mezzi di comunicazione",
    "ambizione",
    "pesca",
    "tema", "saggio",
    "insalata",
    "riparare", "riparazione",
    "oggi",
    "designer", "stilista", "progettista",
    "notte", "serata",
    "banca", "argine", "sponda",
    "disegno", "estrazione",
    "inevitabile",
    "fase",
    "vasto", "immenso",
    "patatina", "chip", "scheggia", "gettone",
    "rabbia", "ira",
    "interruttore", "scambiare", "cambiare",
    "piangere", "grido",
    "torcere", "colpo di scena", "torsione",
    "personalità",
    "tentativo", "tentare",
    "archiviazione", "magazzino", "stoccaggio",
    "essere", "creatura",
    "preparazione",
    "pipistrello", "mazza", "colpire",
    "selezione", "scelta",
    "bianco",
    "tecnologia",
    "contratto", "contrarre",
    "lato", "fianco", "prendere le parti di",
    "sezione", "tratto",
    "stazione", "postazione", "installare",
    "fino a", "cassa", "lavorare il terreno",
    "struttura", "strutturare",
    "lingua",
    "gusto", "assaggiare",
    "verità",
    "difficoltà",
    "gruppo",
    "limite", "limitare",
    "principale",
    "muovere", "mossa", "traslocare",
    "sensazione", "sentimento",
    "luce", "leggero", "accendere",
    "esempio",
    "missione", "mandato",
    "potere", "forza", "potrebbe",
    "aspettare", "attendere",
    "ruota", "volante",
    "negozio", "fare acquisti",
    "ospite", "presentatore", "host",
    "classico",
    "alternativa", "alternativo",
    "causa", "provocare",
    "agente", "rappresentante",
    "consistere",
    "tavolo", "tabella",
    "compagnia aerea",
    "testo", "inviare un messaggio",
    "piscina", "biliardo", "mettere in comune",
    "artigianato", "mestiere", "imbarcazione",
    "gamma", "intervallo", "catena montuosa", "raggio d'azione",
    "carburante", "alimentare",
    "attrezzo", "strumento",
    "partner", "socio", "compagno",
    "caricare", "carico",
    "ingresso", "entrata",
    "deposito", "acconto", "versare",
    "odiare", "odio",
    "articolo",
    "video",
    "estate",
    "caratteristica", "funzione", "articolo di approfondimento",
    "estremo",
    "mobile", "cellulare",
    "ospedale",
    "volo", "fuga",
    "cadere", "autunno",
    "pensione",
    "pianoforte", "piano",
    "fallire", "bocciarsi",
    "risultato", "risultare",
    "strofinare", "sfregare",
    "divario", "fessura", "lacuna",
    "sistema", "impianto",
    "rapporto", "relazione", "segnalare",
    "succhiare", "fare schifo",
    "ordinario", "comune",
    "vento", "avvolgere",
    "nervo", "coraggio",
    "chiedere", "domandare",
    "splendere", "lucidare", "brillare",
    "nota", "notare", "biglietto",
    "linea", "fila", "riga",
    "mamma", "madre",
    "percezione",
    "fratello",
    "riferimento", "referenza", "citazione",
    "piegare", "curva", "ansa",
    "caricare", "accusa", "costo", "incaricare",
    "trattare", "cura", "leccornia",
    "trucco", "ingannare",
    "termine", "semestre", "condizione",
    "compiti", "compiti a casa",
    "cuocere al forno", "infornare",
    "offerta", "offrire",
    "stato", "status",
    "progetto", "proiettare",
    "strategia",
    "arancione", "arancia",
    "lasciare", "affittare",
    "entusiasmo",
    "genitore",
    "concentrarsi", "concentrato",
    "dispositivo", "congegno",
    "viaggiare", "viaggio",
    "poesia",
    "business", "affari", "azienda",
    "società",
    "bacio", "baciare",
    "fine", "terminare",
    "verdura", "vegetale",
    "assumere", "impiegare",
    "programma", "orario", "pianificare",
    "ora",
    "coraggioso",
    "mettere a fuoco", "concentrarsi", "fuoco",
    "processo", "procedimento", "elaborare",
    "film", "pellicola",
    "illegale",
    "generale", "generico",
    "caffè",
    "annuncio", "pubblicità",
    "autostrada", "superstrada",
    "chimica", "alchimia",
    "psicologia",
    "assumere", "noleggiare",
    "campana", "campanello",
    "conferenza", "convegno",
    "sollievo", "rilievo",
    "spettacolo", "mostrare",
    "ordinato", "figo", "liscio",
    "divertente", "strano",
    "peso",
    "qualità",
    "club", "circolo", "mazza",
    "figlia",
    "zona",
    "toccare", "tocco",
    "stasera", "questa notte",
    "shock", "scuotere", "scioccare",
    "bruciare", "ustione",
    "scusa", "giustificazione", "scusare",
    "nome", "nominare",
    "sondaggio", "rilievo", "ispezionare",
    "paesaggio",
    "anticipo", "avanzare",
    "soddisfazione",
    "pane",
    "disastro", "catastrofe",
    "voce", "articolo", "elemento",
    "cappello",
    "precedente", "priore",
    "shopping", "spesa",
    "visitare", "visita",
    "est", "oriente",
    "foto", "fotografia",
    "casa", "abitazione", "in casa",
    "idea",
    "padre", "babbo",
    "confronto", "comparazione",
    "gatto",
    "tubo", "pipa", "condotta",
    "vincitore", "vincitrice",
    "contare", "conte",
    "lago",
    "combattere", "lotta", "rissa",
    "premio",
    "fondazione", "fondamenta", "fondotinta",
    "cane",
    "tenere", "mantenere", "proseguire",
    "ideale",
    "ventilatore", "tifoso", "fan",
    "lotta", "lottare",
    "vetta", "picco", "ora di punta",
    "sicurezza", "salvaguardia",
    "soluzione",
    "inferno", "diavolo!",
    "conclusione", "esito",
    "popolazione",
    "sforzo", "ceppo", "tensione",
    "allarme", "sveglia",
    "misurazione", "misura",
    "secondo", "secondare",
    "treno", "allenare", "addestrare",
    "gara", "razza", "corsa",
    "dovuto", "scadenza", "previsto",
    "assicurazione",
    "capo", "boss",
    "albero",
    "monitor", "sorvegliare",
    "malato", "stufo",
    "corso", "percorso", "certo",
    "trascinare", "seccatura",
    "appuntamento", "nomina",
    "fetta", "affettare",
    "ancora", "immobile", "alambicco",
    "cura", "preoccuparsi", "interessarsi",
    "pazienza",
    "ricco",
    "fuga", "scappare",
    "emozione",
    "reale", "regale",
    "femmina", "femminile",
    "infanzia",
    "governo", "amministrazione",
    "immagine", "foto", "quadro",
    "volontà", "testamento",
    "calzino", "calza",
    "grande",
    "cancello", "gate",
    "olio", "petrolio",
    "croce", "attraversare", "incrociare", "arrabbiato",
    "spillo", "perno", "PIN",
    "miglioramento",
    "campionato", "titolo",
    "sciocco", "stupido",
    "aiuto", "aiutare",
    "cielo",
    "campo", "intonazione", "lancio", "pece",
    "uomo",
    "diamante", "rombo",
    "la maggior parte", "più",
    "transizione", "passaggio",
    "lavoro", "opera", "lavorare",
    "scienza",
    "comitato", "commissione",
    "momento", "istante",
    "riparare", "fissare", "aggiustare", "imbroglio",
    "insegnamento", "didattica",
    "scavare", "frecciatina",
    "specialista",
    "complesso", "complessato",
    "guida", "guidare",
    "persone", "popolo", "gente",
    "morto", "spento",
    "voce",
    "originale",
    "pausa", "rompere", "interruzione",
    "argomento", "tema",
    "dati",
    "grado", "laurea",
    "lettura", "valore letto",
    "registrazione", "incisione",
    "mucchio", "mazzo", "gruppo",
    "raggiungere", "portata",
    "giudizio", "sentenza",
    "bugia", "mentire", "sdraiarsi",
    "regolare", "abituale",
    "insieme", "set", "ambientazione", "fissare",
    "dipinto", "pittura",
    "modalità", "modo",
    "elenco", "lista",
    "giocatore", "lettore",
    "orso", "sopportare", "partorire",
    "nord", "settentrione",
    "chiedersi", "meraviglia",
    "tappeto", "moquette",
    "pesante", "intenso",
    "ufficiale", "funzionario", "agente",
    "negativo",
    "orologio",
    "unico",
    "bambino", "bebè", "neonato",
    "dolore", "pena",
    "assunzione", "supposizione",
    "disco",
    "ferro", "ferro da stiro", "stirare",
    "conto", "fattura", "banconota", "bolletta", "disegno di legge",
    "cassetto", "disegnatore", "traente",
    "guardare", "sguardo", "aspetto",
    "doppio", "raddoppiare",
    "errore", "sbaglio",
    "finire", "fine", "rifinitura",
    "futuro", "avvenire",
    "brillante", "geniale", "luminoso",
    "contatto", "contattare",
    "matematica",
    "riso",
    "lasciare", "partire", "congedo",
    "ristorante",
    "sconto", "scontare",
    "sesso", "rapporti sessuali",
    "virus",
    "briciola", "po'", "bit",
    "fiducia", "fidarsi", "trust (istituto giuridico)",
    "evento", "avvenimento",
    "indossare", "usura", "consumo",
    "succo", "spremuta",
    "fallimento", "guasto", "mancanza",
    "insetto", "bug (errore)", "difetto",
    "contesto",
    "fango",
    "intero", "tutto", "completo",
    "avvolgere", "involtino", "wrap (panino)",
    "intenzione", "proposito",
    "bozza", "leva (militare)", "corrente d'aria",
    "pressione",
    "torta", "dolce",
    "scuro", "buio", "oscuro",
    "spiegazione",
    "spazio", "cosmo",
    "angolo", "angolazione",
    "parola", "promessa",
    "efficienza", "rendimento",
    "gestione", "direzione", "management",
    "abitudine", "abito",
    "stella", "diva",
    "possibilità", "caso", "occasione",
    "ritrovamento", "constatazione", "risultato",
    "trasporto", "trasporti",
    "stare in piedi", "sopportare", "stand (espositore)", "bancarella",
    "critica", "censura",
    "flusso", "scorrere",
    "porta", "portello",
    "lesione", "infortunio", "ferita",
    "insetto",
    "sorpresa", "sorprendere",
    "appartamento",
]

# WORD_LIST = list(set(WORD_LIST_EN + WORD_LIST_IT))
WORD_LIST = WORD_LIST_IT

# ISO 639-1 codes to language names.
LANGUAGE_CODES = immutabledict.immutabledict(
    {
        "en": "English",
        "es": "Spanish",
        "pt": "Portuguese",
        "ar": "Arabic",
        "hi": "Hindi",
        "fr": "French",
        "ru": "Russian",
        "de": "German",
        "ja": "Japanese",
        "it": "Italian",
        "bn": "Bengali",
        "uk": "Ukrainian",
        "th": "Thai",
        "ur": "Urdu",
        "ta": "Tamil",
        "te": "Telugu",
        "bg": "Bulgarian",
        "ko": "Korean",
        "pl": "Polish",
        "he": "Hebrew",
        "fa": "Persian",
        "vi": "Vietnamese",
        "ne": "Nepali",
        "sw": "Swahili",
        "kn": "Kannada",
        "mr": "Marathi",
        "gu": "Gujarati",
        "pa": "Punjabi",
        "ml": "Malayalam",
        "fi": "Finnish",
    }
)

# _ALPHABETS = "([A-Za-z])"
# _PREFIXES = "(Mr|St|Mrs|Ms|Dr)[.]"
# _SUFFIXES = "(Inc|Ltd|Jr|Sr|Co)"
# _STARTERS = r"(Mr|Mrs|Ms|Dr|Prof|Capt|Cpt|Lt|He\s|She\s|It\s|They\s|Their\s|Our\s|We\s|But\s|However\s|That\s|This\s|Wherever)"
# _ACRONYMS = "([A-Z][.][A-Z][.](?:[A-Z][.])?)"
# _WEBSITES = "[.](com|net|org|io|gov|edu|me)"
# _DIGITS = "([0-9])"
# _MULTIPLE_DOTS = r"\.{2,}"

# ITALIAN
_ALPHABETS = "([A-Za-z])"
_PREFIXES = "(Sig.|Sig.ra|Sig.na|Sigg|Dr)[.]"
_SUFFIXES = "(Inc|Ltd|Jr|Sr|Co)"
_STARTERS = r"(Sig.|Sig.ra|Sig.na|Sigg.|Dr|Prof||Lui|Lei|Esso|Loro|Nostro|Noi|Ma|Comunque|Questo|Quello|Comunque)"
_ACRONYMS = "([A-Z][.][A-Z][.](?:[A-Z][.])?)"
_WEBSITES = "[.](com|net|org|io|gov|edu|me)"
_DIGITS = "([0-9])"
_MULTIPLE_DOTS = r"\.{2,}"


def split_into_sentences(text):
    """Split the text into sentences.

    Args:
      text: A string that consists of more than or equal to one sentences.

    Returns:
      A list of strings where each string is a sentence.
    """
    text = " " + text + "  "
    text = text.replace("\n", " ")
    text = re.sub(_PREFIXES, "\\1<prd>", text)
    text = re.sub(_WEBSITES, "<prd>\\1", text)
    text = re.sub(_DIGITS + "[.]" + _DIGITS, "\\1<prd>\\2", text)
    text = re.sub(
        _MULTIPLE_DOTS,
        lambda match: "<prd>" * len(match.group(0)) + "<stop>",
        text,
    )
    if "Ph.D" in text:
        text = text.replace("Ph.D.", "Ph<prd>D<prd>")
    text = re.sub(r"\s" + _ALPHABETS + "[.] ", " \\1<prd> ", text)
    text = re.sub(_ACRONYMS + " " + _STARTERS, "\\1<stop> \\2", text)
    text = re.sub(
        _ALPHABETS + "[.]" + _ALPHABETS + "[.]" + _ALPHABETS + "[.]",
        "\\1<prd>\\2<prd>\\3<prd>",
        text,
    )
    text = re.sub(_ALPHABETS + "[.]" + _ALPHABETS + "[.]", "\\1<prd>\\2<prd>", text)
    text = re.sub(" " + _SUFFIXES + "[.] " + _STARTERS, " \\1<stop> \\2", text)
    text = re.sub(" " + _SUFFIXES + "[.]", " \\1<prd>", text)
    text = re.sub(" " + _ALPHABETS + "[.]", " \\1<prd>", text)
    if "”" in text:
        text = text.replace(".”", "”.")
    if '"' in text:
        text = text.replace('."', '".')
    if "!" in text:
        text = text.replace('!"', '"!')
    if "?" in text:
        text = text.replace('?"', '"?')
    text = text.replace(".", ".<stop>")
    text = text.replace("?", "?<stop>")
    text = text.replace("!", "!<stop>")
    text = text.replace("<prd>", ".")
    sentences = text.split("<stop>")
    sentences = [s.strip() for s in sentences]
    if sentences and not sentences[-1]:
        sentences = sentences[:-1]
    return sentences


def count_words(text):
    """Counts the number of words."""
    tokenizer = nltk.tokenize.RegexpTokenizer(r"\w+")
    tokens = tokenizer.tokenize(text)
    num_words = len(tokens)
    return num_words


@functools.lru_cache(maxsize=None)
def _get_sentence_tokenizer():
    return nltk.data.load("nltk:tokenizers/punkt/italian.pickle")


def count_sentences(text):
    """Count the number of sentences."""
    tokenizer = _get_sentence_tokenizer()
    tokenized_sentences = tokenizer.tokenize(text)
    return len(tokenized_sentences)


def generate_keywords(num_keywords):
    """Randomly generates a few keywords."""
    return random.sample(WORD_LIST, k=num_keywords)
